name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: AdrianoVS87
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          config_timezone: America/Sao_Paulo
